apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: nsmysql
  labels:
    app: mysql
    owner: Darshil
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    ports:
    - name: mysql
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password