apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlreplicaset
  namespace: nsmysql
  labels:
    app: mysql
    owner: darshil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"