apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: nsapp
  labels:
    app: employees
    owner: Darshil
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employees